version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3-stretch-node-browsers
    steps:
      - run: # sudo apt update && sudo apt install git -y && git --version
          name:  update and install
          command: sudo apt update && sudo apt install git -y && git --version

      # Update environment
      - run:
          name: apt update
          command: sudo apt update
      # Install rsync. It will be used to upload our code to server
      - run: sudo apt-get install rsync

      # Sync the SSH keys 
      - add_ssh_keys

      # Check out the code in the project directory
      - checkout

      # Install JS dependencies.
      # Of course, you may not need this. It just shows how to use some commands such as npm
      - run: npm install

      # Run your command
      - run: npm run build

      # Add the server to known hosts
      - run: ssh-keyscan -H $HOST >> ~/.ssh/known_hosts

      # Finally, upload your files to server.
      - run: rsync -avce ssh --delete ./dist/ $USER@$HOST:$HOSTGATOR_WORKING_DIRECTORY